### PR TITLE
Header needed in archlinux

### PR DESCRIPTION
**Pull request by lf-araujo**
This solves the problem of building apps with this library in archlinux.

### CODE REVIEW

**Comment by TomasLinhart** [comment]
Does this also work with Ubuntu?

**Comment by lf-araujo** [comment]
I haven't tested, I don't have a ubuntu machine... sorry... I am running on Manjaro-arch.

**Comment by bmdelacruz** [comment]
it worked on ubuntu (16.04)

**Comment by TomasLinhart** [comment]
Thanks!

**Pull request merged**
